name: skill_race
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bot_toast: ^4.0.4
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  flutter_screenutil: ^5.9.0
  flutter_svg: null
  go_router: ^10.1.0
  lottie: ^2.6.0
  reactive_forms: ^16.1.0
  reactive_forms_generator: ^4.0.0

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
