name: skill_race
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bot_toast: ^4.0.4
  cloud_firestore: ^4.9.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.10
  flutter_riverpod: ^2.3.7
  flutter_screenutil: ^5.9.0
  riverpod_annotation:
  flutter_svg: null
  freezed_annotation: ^2.4.1
  go_router: ^10.1.0
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  onboarding_animation: ^0.0.3
  reactive_date_time_picker: ^3.0.0
  reactive_dropdown_search: ^3.0.0
  reactive_forms: ^16.1.0
  reactive_forms_generator: ^4.0.0
  reactive_phone_form_field: ^2.0.0
  riverpod_generator: ^2.2.6
  # shimmer: ^3.0.0
  icons_plus: ^4.0.0
  
dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/svg/onboarding/
    - assets/images/png/
    - assets/json/
    - assets/icons/
    - assets/icons/png/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
